### ISSUE TITLE
Can I generete COM object with this stuff?

### ISSUE THREAD

**Issue by frenchfish** [lordmilko/ClrDebug#12]
Hello I want to make simple COM Object and I need to generate COM interfaces for it?
Do I need helpers,or generators, or I should use just [DLLImport] attributes? which will make tbl and register it with regasm or Compile Com=true  settings in VS etc?

**Comment by lordmilko** [comment]
This library is a set of COM interfaces and C# wrappers around those interfaces for the purposes of developing debugging/diagnostic tools.

Are you able to clarify what you're asking exactly?

**Comment by frenchfish** [comment]
Debuging is advanced stage. I need simple Com interfaces like IDispatch implementation via C# (InteropServices) generate them automatically.So maybe there is a way t o generate unsave code and IDL, tlb with low level tools like yours
Think about it like a challenge. :-)
So I would like to see simple COM object Server implementation,which can be consumed by unmanaged clients c++ vb6 etc

**Comment by lordmilko** [comment]
The COM interfaces contained in this repo were either hand crafted or generated via tlbimp.exe. If you are looking to get C# definitions of an existing COM interface you will need to convert an IDL/TLB file using midl and/or tlbimp and then decompile the DLL using something like dotPeek. This repo then contains a set of C# classes that wrap the raw COM interfaces for easier consumption within C#.

You seem to be indicating that you want to write a COM server in C# to be consumed by other languages. This query is not related to this repo and is not something I can help with; you can find information about how to write a COM server in C# on Google

**Comment by frenchfish** [comment]
yes,thanks i am looking for simple stuff yet. Debuggin is next step Ж-)
