### ISSUE TITLE
Confusion around ICorDebugEval interface - CallParameterizedFunction

### ISSUE THREAD

**Issue by christophediericx** [lordmilko/ClrDebug#13]
I have been trying to use both `CallFunction` and `CallParameterizedFunction` (the first just dispatches to the second anyway I believe) to evaluate a call to a `ToString()` method reference, and have been experiencing difficulties in doing so (e.g., always ending up with `EvalExceptionCorDebugManagedCallbackEventArgs` in the managed callback rather than `EvalCompleteCorDebugManagedCallbackEventArgs`. 

Inspecting the underlying `CorDebugValue`s in those I'm always running into `System.ArgumentException` or `System.Reflection.TargetParameterCountException`.

Looking at the way `ClrDebug` (I'm using version 0.3.2) marshals these methods, I noticed that it doesn't use array types for the arguments (`ppTypeArgs`, `ppArgs`), 

```
[PreserveSig]
HRESULT CallParameterizedFunction([In][MarshalAs(UnmanagedType.Interface)] ICorDebugFunction pFunction, [In] int nTypeArgs, [In][MarshalAs(UnmanagedType.Interface)] ref ICorDebugType ppTypeArgs, [In] int nArgs, [In][MarshalAs(UnmanagedType.Interface)] ref ICorDebugValue ppArgs);
```

which I would expect when looking at e.g., the `mdbg` implementation:

```
void CallParameterizedFunction([In, MarshalAs(UnmanagedType.Interface)] ICorDebugFunction pFunction, [In] uint nTypeArgs, [In, MarshalAs(UnmanagedType.LPArray, SizeParamIndex = 1)] ICorDebugType[] ppTypeArgs, [In] uint nArgs, [In, MarshalAs(UnmanagedType.LPArray, SizeParamIndex = 3)] ICorDebugValue[] ppArgs);
```

and the unmanaged API reference - https://learn.microsoft.com/en-us/dotnet/framework/unmanaged-api/debugging/icordebugeval2-callparameterizedfunction-method

Is it possible this particular API has a small mismatch, or do I simply misunderstand how to use it correctly? I don't really find any code samples / references in the `ClrDebug` repository itself.

Thanks a lot in advance for any guidance you would be able to provide.

**Comment by lordmilko** [comment]
Hi @christophediericx,

Thanks for reporting this issue. You're right, the parameter types on these methods are incorrect. When you create managed COM definitions out of an `*.idl` file using Tlbimp, it introduces many types of errors that need to manually be audited and corrected, in particular with any parameters that are arrays (since in "true COM" it is technically illegal to use a C style array). While I've done several audits on ClrDebug's interface definitions to make sure they're correct, evidently I have still missed some.

I will conduct another audit of all `ref` parameters to see if there are any others that I've missed

Regards,
lordmilko

**Comment by lordmilko** [comment]
Hi @christophediericx,

I have pushed a fix that I believe should fix this issue. Are you able to test [the latest build](https://ci.appveyor.com/api/buildjobs/3h9f03ediq6r57lm/artifacts/ClrDebug.zip) and advise if this resolves your issue?

**Comment by christophediericx** [comment]
@lordmilko Thanks you so much for the amazing turnaround time (and the great work on `ClrDebug` of course)! I will grab the latest build and will provide feedback either later today or at the latest tomorrow.

**Comment by christophediericx** [comment]
I can confirm this fix works as intended - I have no problem triggering `EvalComplete` with this.

Thanks!
